### ISSUE TITLE
Questions about image drawing tool

### ISSUE THREAD

**Issue by jlarfors** [colinwilson/colinwilson.uk#293]
Hey Colin!

I came across your blog and the content is awesome and the website itself is just beautiful! Awesome work.

I had to ask, hence this issue, which tool do you use for drawing these diagrams?

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1135394/203141421-a4ee657c-5b20-44bc-a409-5f01000e89f3.png">

Keep up the great work!

**Comment by colinwilson** [comment]
Thanks for the very kind words @jlarfors, glad you like my site.

I created the all the diagrams in that post using Adobe Illustrator (so no drawing tool I'm afraid). It takes time, but sometimes various drawing tools just can't quite visualize certain concepts to my satisfaction.

**Comment by jlarfors** [comment]
Interesting, thanks @colinwilson for the info. I was hoping there was some nice, OSS, tech-focused tool out there for this...

Anyway, keep up the excellent work!

**Comment by colinwilson** [comment]
Thanks again, much appreciated. 👍
